### ISSUE TITLE
epic: create schemas (attests) logic on resolver contract

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/trustful-zuzalu-contracts#5]
Definition of Done:

- [x] Elaborate logic to handle different schemas in a single resolver
- [x] Create mappings, getters and setters for resolver configuration
- [x] #7
- [x] #6 
- [x] #12
- [x] Revoke an attestation
- [x] Switch from checkIn to checkOut
- [x] Create response attestation

**Comment by 0xneves** [comment]
Let's change the villager schema into revocable instead of creating a badge for each action: check-in and checkout. This will result in a schema exactly like the manager schema, so I'll have to store a mock input to make the abi different. Adding "address villager" will be a duplicated field from `attestation.recipient` but will help organize the schemas. 

A nice proposal for EAS is to allow for a naming convention when hashing the schema uid or versioning inside a schema to make it different schemas with the same data types.

**Comment by 0xneves** [comment]
My fault, this is not a solution, because only the manager can revoke the checkIn attestation, but we actually need the user to revoke it.
